### ISSUE TITLE
Exception in thread "Thread-6" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jigaoxiang** [mkirsche/Jasmine#42]
Dear Dr，
When I merge the 25 SV files，there is some errors about my memory？My commad line as below:
`jasmine file_list=merge1.txt out_file=merge.n.vcf out_dir=./ threads=6`
And the error information as show follow:
```
Exception in thread "Thread-6" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.PriorityQueue.grow(PriorityQueue.java:305)
        at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:344)
        at java.base/java.util.PriorityQueue.add(PriorityQueue.java:326)
        at KDTree.search(KDTree.java:244)
        at KDTree.kNearestNeighbor(KDTree.java:197)
        at VariantMerger.runMerging(VariantMerger.java:205)
        at ParallelMerger$MyThread.run(ParallelMerger.java:89)
```
Can you give some advice to deal with this?
Thank your time!
Best wishes

Ji gaoxiang

**Comment by mas-agis** [comment]
Hi, 
I run into the same problem.
Did you find the way to figure it out?
Best,
Maulana

**Comment by christopher-schroeder** [comment]
Just increase the java memory

`jasmine file_list=merge1.txt out_file=merge.n.vcf out_dir=./ threads=6 -Xmx50g`

Best

**Comment by hayley-power** [comment]
Does the -Xmx option selection definitely go at the end of the jasmine command?
