### ISSUE TITLE
a sequence name but not an actual sequence

### ISSUE THREAD

**Issue by aojielian** [mkirsche/Jasmine#45]
Hi,
when i run Jasmine, i got an error 
Outputting original deletion for GL000009.2:20426:DEL:Sniffles2.DEL.1DS1A (time = 00:00:01:25.032)
Exception in thread "main" java.lang.Exception: samtools faidx produced a sequence name but not an actual sequence: samtools faidx /home/a1lian/hg38.fa GL000009.2:20427-20488
	at IrisGenomeQuery.genomeSubstring(IrisGenomeQuery.java:62)
	at VcfEditor.run(VcfEditor.java:227)
	at Iris.runIris(Iris.java:21)
	at PipelineManager.runIris(PipelineManager.java:129)
	at Main.preprocess(Main.java:47)
	at Main.main(Main.java:17)

**Comment by noorsmal** [comment]
I had the same issue. For me it was caused by the --normalize-chrs option that changed the chromosome names from chr1 -> 1. This then caused the chromosome names not to be present in my reference genome fasta file. It was solved by removing that option.
