### ISSUE TITLE
allow_intrasample throws exceptions

### ISSUE THREAD

**Issue by jasonbhn** [mkirsche/Jasmine#58]
hi Melanie, 
I'm trying to combine multiple caller's SV calls into 1 vcf, the --allow_intrasample option seems like the natural way to go. but i've been running into this exception here:
```java
Exception in thread "main" java.lang.NumberFormatException: For input string: "SUPP"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at VariantOutput$VariantGraph.updateOutputVariant(VariantOutput.java:407)
	at VariantOutput$VariantGraph.processVariant(VariantOutput.java:645)
	at VariantOutput.writeMergedVariants(VariantOutput.java:128)
	at Main.runJasmine(Main.java:76)
	at Main.main(Main.java:22)
```
Any idea how I can get more detail on what's wrong?

Thanks

**Comment by YannLeGuen** [comment]
Same question here ..

Any clues?
